version: '3.2'
services:
  web:
    #build: .
    image: fauria/lamp
    ports:
      - "80:80"
    volumes:
      -  /Users/lanzruiz/Desktop/Files/Project/shoptexto:/var/www/html
    environment:
        - ALLOW_OVERRIDE=true
